# Generated by Django 4.2 on 2026-01-06 04:11

from django.db import migrations, models
import django.db.models.deletion
import session_manager.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="Anonymous", max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[("sender", "Sender"), ("receiver", "Receiver")],
                        default="receiver",
                        max_length=10,
                    ),
                ),
                ("target_language", models.CharField(max_length=10)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("channel_name", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "room_code",
                    models.CharField(
                        db_index=True,
                        default=session_manager.models.generate_room_code,
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("sender_name", models.CharField(default="Anonymous", max_length=100)),
                ("source_language", models.CharField(default="en", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_audio",
                    models.FileField(
                        blank=True, null=True, upload_to="session_audio/original/"
                    ),
                ),
                ("transcription", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to="session_manager.participant",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="session_manager.session",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_language", models.CharField(max_length=10)),
                ("translated_text", models.TextField()),
                (
                    "translated_audio",
                    models.FileField(
                        blank=True, null=True, upload_to="session_audio/translated/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="session_manager.sessionmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["room_code", "is_active"], name="session_man_room_co_515fa3_idx"
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="session_manager.session",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="translation",
            unique_together={("message", "target_language")},
        ),
        migrations.AddIndex(
            model_name="sessionmessage",
            index=models.Index(
                fields=["session", "created_at"], name="session_man_session_067c92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="participant",
            index=models.Index(
                fields=["session", "is_active"], name="session_man_session_73f10a_idx"
            ),
        ),
    ]
