# Generated by Django 4.2 on 2026-01-06 03:46

from django.db import migrations, models
import django.db.models.deletion
import room_handler.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_code",
                    models.CharField(
                        default=room_handler.models.generate_room_code,
                        help_text="Unique room code for joining (e.g., ABC-123)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "sender_language",
                    models.CharField(
                        help_text="Language code of the sender (e.g., 'en', 'es')",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        help_text="WebSocket session identifier", max_length=100
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("sender", "Sender"), ("receiver", "Receiver")],
                        help_text="Participant role in the room",
                        max_length=10,
                    ),
                ),
                (
                    "target_language",
                    models.CharField(
                        help_text="Preferred language for receiving translations",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_connected", models.BooleanField(default=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="room_handler.room",
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        help_text="Original audio file from sender",
                        upload_to="room_audio/original/%Y/%m/%d/",
                    ),
                ),
                (
                    "transcription",
                    models.TextField(
                        blank=True, help_text="Transcribed text from audio"
                    ),
                ),
                (
                    "translations",
                    models.JSONField(
                        default=dict,
                        help_text="Translations by language code: {lang: text}",
                    ),
                ),
                (
                    "translated_audio_files",
                    models.JSONField(
                        default=dict,
                        help_text="Translated audio file paths by language: {lang: path}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="room_handler.room",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["room_code"], name="room_handle_room_co_b3dd7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["is_active", "-created_at"],
                name="room_handle_is_acti_f6fe90_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roomparticipant",
            index=models.Index(
                fields=["room", "is_connected"], name="room_handle_room_id_5663fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roomparticipant",
            index=models.Index(
                fields=["session_id"], name="room_handle_session_98befd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roommessage",
            index=models.Index(
                fields=["room", "created_at"], name="room_handle_room_id_c59ab8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roommessage",
            index=models.Index(
                fields=["processing_status"], name="room_handle_process_b3375d_idx"
            ),
        ),
    ]
